// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: exchangeRate.proto

package server_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ExchangeRateService_GetLatestRate_FullMethodName = "/exchangeRate.v1.exchangeRateService/getLatestRate"
	ExchangeRateService_GetRangeRate_FullMethodName  = "/exchangeRate.v1.exchangeRateService/getRangeRate"
)

// ExchangeRateServiceClient is the client API for ExchangeRateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeRateServiceClient interface {
	// Sends a greeting
	GetLatestRate(ctx context.Context, in *GetLatestRateRequest, opts ...grpc.CallOption) (*GetLatestRateResponse, error)
	GetRangeRate(ctx context.Context, in *GetRangeRateRequest, opts ...grpc.CallOption) (*GetRangeRateResponse, error)
}

type exchangeRateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeRateServiceClient(cc grpc.ClientConnInterface) ExchangeRateServiceClient {
	return &exchangeRateServiceClient{cc}
}

func (c *exchangeRateServiceClient) GetLatestRate(ctx context.Context, in *GetLatestRateRequest, opts ...grpc.CallOption) (*GetLatestRateResponse, error) {
	out := new(GetLatestRateResponse)
	err := c.cc.Invoke(ctx, ExchangeRateService_GetLatestRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeRateServiceClient) GetRangeRate(ctx context.Context, in *GetRangeRateRequest, opts ...grpc.CallOption) (*GetRangeRateResponse, error) {
	out := new(GetRangeRateResponse)
	err := c.cc.Invoke(ctx, ExchangeRateService_GetRangeRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeRateServiceServer is the server API for ExchangeRateService service.
// All implementations must embed UnimplementedExchangeRateServiceServer
// for forward compatibility
type ExchangeRateServiceServer interface {
	// Sends a greeting
	GetLatestRate(context.Context, *GetLatestRateRequest) (*GetLatestRateResponse, error)
	GetRangeRate(context.Context, *GetRangeRateRequest) (*GetRangeRateResponse, error)
	mustEmbedUnimplementedExchangeRateServiceServer()
}

// UnimplementedExchangeRateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeRateServiceServer struct {
}

func (UnimplementedExchangeRateServiceServer) GetLatestRate(context.Context, *GetLatestRateRequest) (*GetLatestRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRate not implemented")
}
func (UnimplementedExchangeRateServiceServer) GetRangeRate(context.Context, *GetRangeRateRequest) (*GetRangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRangeRate not implemented")
}
func (UnimplementedExchangeRateServiceServer) mustEmbedUnimplementedExchangeRateServiceServer() {}

// UnsafeExchangeRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeRateServiceServer will
// result in compilation errors.
type UnsafeExchangeRateServiceServer interface {
	mustEmbedUnimplementedExchangeRateServiceServer()
}

func RegisterExchangeRateServiceServer(s grpc.ServiceRegistrar, srv ExchangeRateServiceServer) {
	s.RegisterService(&ExchangeRateService_ServiceDesc, srv)
}

func _ExchangeRateService_GetLatestRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeRateServiceServer).GetLatestRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeRateService_GetLatestRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeRateServiceServer).GetLatestRate(ctx, req.(*GetLatestRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeRateService_GetRangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeRateServiceServer).GetRangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeRateService_GetRangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeRateServiceServer).GetRangeRate(ctx, req.(*GetRangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeRateService_ServiceDesc is the grpc.ServiceDesc for ExchangeRateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeRateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchangeRate.v1.exchangeRateService",
	HandlerType: (*ExchangeRateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getLatestRate",
			Handler:    _ExchangeRateService_GetLatestRate_Handler,
		},
		{
			MethodName: "getRangeRate",
			Handler:    _ExchangeRateService_GetRangeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchangeRate.proto",
}
